/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controleur.Controle;
   import javax.swing.JFrame;
//import static javax.swing.JFrame.EXIT_ON_CLOSE;

/**
 *
 * @author Administrateur
 */
public class EntreeJeu extends JFrame {

    /**
     * Creates new form EntreeJeu
     */
    private Controle controle;
    
    public EntreeJeu(Controle ctrl) {
        super();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        initComponents();
        controle = ctrl;
        
    }

    private void cmdServeur_clic(){
        controle.EvenementVue(this, "serveur");
    }
    
    private void cmdClient_clic(){
          controle.EvenementVue(this, txtIP.getText());
    }
    
    private void cmdQuitter_clic(){
         System.exit(0);
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmdQuitter = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtIP = new javax.swing.JTextField();
        javax.swing.JButton cmdServeur = new javax.swing.JButton();
        cmdConnecter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Urban Marginal");
        setMinimumSize(new java.awt.Dimension(350, 200));
        getContentPane().setLayout(null);

        jLabel1.setText("IP Serveur");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 90, 80, 30);

        jLabel2.setBackground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Je veux me connecter à un serveur existant");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 250, 30);

        cmdQuitter.setText("Quitter");
        cmdQuitter.setName("cmdQuitter"); // NOI18N
        cmdQuitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdQuitterMouseClicked(evt);
            }
        });
        getContentPane().add(cmdQuitter);
        cmdQuitter.setBounds(210, 120, 90, 23);

        jLabel4.setText("Je veux être un serveur");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 10, 150, 30);

        txtIP.setText("127.0.0.1");
        txtIP.setName("textIP"); // NOI18N
        getContentPane().add(txtIP);
        txtIP.setBounds(100, 90, 100, 30);

        cmdServeur.setText("Démarrer");
        cmdServeur.setName("cmdServeur"); // NOI18N
        cmdServeur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdServeurMouseClicked(evt);
            }
        });
        getContentPane().add(cmdServeur);
        cmdServeur.setBounds(210, 10, 90, 23);

        cmdConnecter.setText("Connecter");
        cmdConnecter.setName("cmdClient"); // NOI18N
        cmdConnecter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdConnecterMouseClicked(evt);
            }
        });
        getContentPane().add(cmdConnecter);
        cmdConnecter.setBounds(210, 90, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void cmdServeurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdServeurMouseClicked
        
        cmdServeur_clic();   
    }//GEN-LAST:event_cmdServeurMouseClicked

    private void cmdQuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdQuitterMouseClicked
        
        cmdQuitter_clic();  
    }//GEN-LAST:event_cmdQuitterMouseClicked

    private void cmdConnecterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdConnecterMouseClicked
        
         cmdClient_clic();
    }//GEN-LAST:event_cmdConnecterMouseClicked

     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdConnecter;
    private javax.swing.JButton cmdQuitter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtIP;
    // End of variables declaration//GEN-END:variables
}
